// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SGExtens.proto

package com.douqu.game.core.protobuf;

public final class SGExtensProto {
  private SGExtensProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016SGExtens.proto\032\016SGCommon.protoB5\n\034com." +
      "douqu.game.core.protobufB\rSGExtensProto\252" +
      "\002\005UBaseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.douqu.game.core.protobuf.SGCommonProto.getDescriptor(),
        }, assigner);
    com.douqu.game.core.protobuf.SGCommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
