// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SGMain.proto

package com.douqu.game.core.protobuf;

public final class SGMainProto {
  private SGMainProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code E_MSG_TYPE}
   */
  public enum E_MSG_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * </pre>
     *
     * <code>MsgType_NeverUse = 0;</code>
     */
    MsgType_NeverUse(0),
    /**
     * <pre>
     *关闭服务器
     * </pre>
     *
     * <code>MsgType_Close = 9999;</code>
     */
    MsgType_Close(9999),
    /**
     * <pre>
     *战斗类型的消息
     * </pre>
     *
     * <code>MsgType_Battle = 200;</code>
     */
    MsgType_Battle(200),
    /**
     * <pre>
     *玩家类型消息
     * </pre>
     *
     * <code>MsgType_Player = 300;</code>
     */
    MsgType_Player(300),
    /**
     * <pre>
     *世界类型消息
     * </pre>
     *
     * <code>MsgType_World = 400;</code>
     */
    MsgType_World(400),
    /**
     * <pre>
     *背包类型消息
     * </pre>
     *
     * <code>MsgType_Bag = 500;</code>
     */
    MsgType_Bag(500),
    /**
     * <pre>
     *副本类型消息
     * </pre>
     *
     * <code>MsgType_Instance = 600;</code>
     */
    MsgType_Instance(600),
    /**
     * <pre>
     *竞技场类型消息
     * </pre>
     *
     * <code>MsgType_Arena = 700;</code>
     */
    MsgType_Arena(700),
    /**
     * <pre>
     *酒馆类型消息
     * </pre>
     *
     * <code>MsgType_Lottery = 800;</code>
     */
    MsgType_Lottery(800),
    /**
     * <pre>
     *祭坛类型消息
     * </pre>
     *
     * <code>MsgType_Altar = 900;</code>
     */
    MsgType_Altar(900),
    /**
     * <pre>
     *官阶战类型消息
     * </pre>
     *
     * <code>MsgType_OfficialWar = 1000;</code>
     */
    MsgType_OfficialWar(1000),
    /**
     * <pre>
     *任务类型消息
     * </pre>
     *
     * <code>MsgType_Task = 1100;</code>
     */
    MsgType_Task(1100),
    /**
     * <pre>
     *商店类型消息
     * </pre>
     *
     * <code>MsgType_Store = 1200;</code>
     */
    MsgType_Store(1200),
    /**
     * <pre>
     *英雄圣殿类型消息
     * </pre>
     *
     * <code>MsgType_HeroTemple = 1300;</code>
     */
    MsgType_HeroTemple(1300),
    /**
     * <pre>
     *邮件类型消息
     * </pre>
     *
     * <code>MsgType_Mail = 1400;</code>
     */
    MsgType_Mail(1400),
    /**
     * <pre>
     *充值和福利消息
     * </pre>
     *
     * <code>MsgType_Bonus = 1500;</code>
     */
    MsgType_Bonus(1500),
    /**
     * <pre>
     *远征副本消息
     * </pre>
     *
     * <code>MsgType_Expedition = 1600;</code>
     */
    MsgType_Expedition(1600),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * </pre>
     *
     * <code>MsgType_NeverUse = 0;</code>
     */
    public static final int MsgType_NeverUse_VALUE = 0;
    /**
     * <pre>
     *关闭服务器
     * </pre>
     *
     * <code>MsgType_Close = 9999;</code>
     */
    public static final int MsgType_Close_VALUE = 9999;
    /**
     * <pre>
     *战斗类型的消息
     * </pre>
     *
     * <code>MsgType_Battle = 200;</code>
     */
    public static final int MsgType_Battle_VALUE = 200;
    /**
     * <pre>
     *玩家类型消息
     * </pre>
     *
     * <code>MsgType_Player = 300;</code>
     */
    public static final int MsgType_Player_VALUE = 300;
    /**
     * <pre>
     *世界类型消息
     * </pre>
     *
     * <code>MsgType_World = 400;</code>
     */
    public static final int MsgType_World_VALUE = 400;
    /**
     * <pre>
     *背包类型消息
     * </pre>
     *
     * <code>MsgType_Bag = 500;</code>
     */
    public static final int MsgType_Bag_VALUE = 500;
    /**
     * <pre>
     *副本类型消息
     * </pre>
     *
     * <code>MsgType_Instance = 600;</code>
     */
    public static final int MsgType_Instance_VALUE = 600;
    /**
     * <pre>
     *竞技场类型消息
     * </pre>
     *
     * <code>MsgType_Arena = 700;</code>
     */
    public static final int MsgType_Arena_VALUE = 700;
    /**
     * <pre>
     *酒馆类型消息
     * </pre>
     *
     * <code>MsgType_Lottery = 800;</code>
     */
    public static final int MsgType_Lottery_VALUE = 800;
    /**
     * <pre>
     *祭坛类型消息
     * </pre>
     *
     * <code>MsgType_Altar = 900;</code>
     */
    public static final int MsgType_Altar_VALUE = 900;
    /**
     * <pre>
     *官阶战类型消息
     * </pre>
     *
     * <code>MsgType_OfficialWar = 1000;</code>
     */
    public static final int MsgType_OfficialWar_VALUE = 1000;
    /**
     * <pre>
     *任务类型消息
     * </pre>
     *
     * <code>MsgType_Task = 1100;</code>
     */
    public static final int MsgType_Task_VALUE = 1100;
    /**
     * <pre>
     *商店类型消息
     * </pre>
     *
     * <code>MsgType_Store = 1200;</code>
     */
    public static final int MsgType_Store_VALUE = 1200;
    /**
     * <pre>
     *英雄圣殿类型消息
     * </pre>
     *
     * <code>MsgType_HeroTemple = 1300;</code>
     */
    public static final int MsgType_HeroTemple_VALUE = 1300;
    /**
     * <pre>
     *邮件类型消息
     * </pre>
     *
     * <code>MsgType_Mail = 1400;</code>
     */
    public static final int MsgType_Mail_VALUE = 1400;
    /**
     * <pre>
     *充值和福利消息
     * </pre>
     *
     * <code>MsgType_Bonus = 1500;</code>
     */
    public static final int MsgType_Bonus_VALUE = 1500;
    /**
     * <pre>
     *远征副本消息
     * </pre>
     *
     * <code>MsgType_Expedition = 1600;</code>
     */
    public static final int MsgType_Expedition_VALUE = 1600;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static E_MSG_TYPE valueOf(int value) {
      return forNumber(value);
    }

    public static E_MSG_TYPE forNumber(int value) {
      switch (value) {
        case 0: return MsgType_NeverUse;
        case 9999: return MsgType_Close;
        case 200: return MsgType_Battle;
        case 300: return MsgType_Player;
        case 400: return MsgType_World;
        case 500: return MsgType_Bag;
        case 600: return MsgType_Instance;
        case 700: return MsgType_Arena;
        case 800: return MsgType_Lottery;
        case 900: return MsgType_Altar;
        case 1000: return MsgType_OfficialWar;
        case 1100: return MsgType_Task;
        case 1200: return MsgType_Store;
        case 1300: return MsgType_HeroTemple;
        case 1400: return MsgType_Mail;
        case 1500: return MsgType_Bonus;
        case 1600: return MsgType_Expedition;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<E_MSG_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        E_MSG_TYPE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<E_MSG_TYPE>() {
            public E_MSG_TYPE findValueByNumber(int number) {
              return E_MSG_TYPE.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.douqu.game.core.protobuf.SGMainProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final E_MSG_TYPE[] VALUES = values();

    public static E_MSG_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private E_MSG_TYPE(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:E_MSG_TYPE)
  }

  /**
   * Protobuf enum {@code E_MSG_ID}
   */
  public enum E_MSG_ID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *不使用,proto3枚举首项值必为0
     * </pre>
     *
     * <code>MsgID_NeverUse = 0;</code>
     */
    MsgID_NeverUse(0),
    /**
     * <pre>
     *注册
     * </pre>
     *
     * <code>MsgID_System_Regist = 101;</code>
     */
    MsgID_System_Regist(101),
    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>MsgID_System_Login = 102;</code>
     */
    MsgID_System_Login(102),
    /**
     * <pre>
     *心跳检测
     * </pre>
     *
     * <code>MsgID_System_Ping = 103;</code>
     */
    MsgID_System_Ping(103),
    /**
     * <pre>
     *获取验证码
     * </pre>
     *
     * <code>MsgID_System_GetCaptcha = 104;</code>
     */
    MsgID_System_GetCaptcha(104),
    /**
     * <pre>
     *统一的一个通知消息
     * </pre>
     *
     * <code>MsgID_System_NotifyAlert = 105;</code>
     */
    MsgID_System_NotifyAlert(105),
    /**
     * <pre>
     *退出登录
     * </pre>
     *
     * <code>MsgID_System_Logout = 106;</code>
     */
    MsgID_System_Logout(106),
    /**
     * <pre>
     *登录,开发用
     * </pre>
     *
     * <code>MsgID_System_SuperLogin = 199;</code>
     */
    MsgID_System_SuperLogin(199),
    /**
     * <pre>
     *战斗服务器重连
     * </pre>
     *
     * <code>MsgID_System_BattleReconnect = 110;</code>
     */
    MsgID_System_BattleReconnect(110),
    /**
     * <pre>
     *cmd
     * </pre>
     *
     * <code>MsgID_System_GMCmd = 111;</code>
     */
    MsgID_System_GMCmd(111),
    /**
     * <pre>
     *顶号
     * </pre>
     *
     * <code>MsgID_System_LoginOtherPlace = 112;</code>
     */
    MsgID_System_LoginOtherPlace(112),
    /**
     * <pre>
     *取消等待
     * </pre>
     *
     * <code>MsgID_System_CancelWait = 113;</code>
     */
    MsgID_System_CancelWait(113),
    /**
     * <pre>
     *因为某些原因离线了,通知客户端
     * </pre>
     *
     * <code>MsgID_System_Offline = 114;</code>
     */
    MsgID_System_Offline(114),
    /**
     * <pre>
     *创建战斗
     * </pre>
     *
     * <code>MsgID_War_Create = 201;</code>
     */
    MsgID_War_Create(201),
    /**
     * <pre>
     *上战场(卡牌放出去)
     * </pre>
     *
     * <code>MsgID_War_ToBattle = 202;</code>
     */
    MsgID_War_ToBattle(202),
    /**
     * <pre>
     *敌对的兵相遇了，要开战了
     * </pre>
     *
     * <code>MsgID_War_SoldierBattleStart = 203;</code>
     */
    MsgID_War_SoldierBattleStart(203),
    /**
     * <pre>
     *战斗结果
     * </pre>
     *
     * <code>MsgID_War_SynResult = 204;</code>
     */
    MsgID_War_SynResult(204),
    /**
     * <pre>
     *使用技能
     * </pre>
     *
     * <code>MsgID_War_UseSkill = 205;</code>
     */
    MsgID_War_UseSkill(205),
    /**
     * <pre>
     *添加效果
     * </pre>
     *
     * <code>MsgID_War_AddEffect = 206;</code>
     */
    MsgID_War_AddEffect(206),
    /**
     * <pre>
     *移除效果
     * </pre>
     *
     * <code>MsgID_War_RemoveEffect = 207;</code>
     */
    MsgID_War_RemoveEffect(207),
    /**
     * <pre>
     *刷新效果剩余持续时间
     * </pre>
     *
     * <code>MsgID_War_UpdateEffectDuration = 208;</code>
     */
    MsgID_War_UpdateEffectDuration(208),
    /**
     * <pre>
     *对象死亡
     * </pre>
     *
     * <code>MsgID_War_ObjectDie = 209;</code>
     */
    MsgID_War_ObjectDie(209),
    /**
     * <pre>
     *同步位置
     * </pre>
     *
     * <code>MsgID_War_SynPos = 210;</code>
     */
    MsgID_War_SynPos(210),
    /**
     * <pre>
     *伤害同步
     * </pre>
     *
     * <code>MsgID_War_DoDamage = 211;</code>
     */
    MsgID_War_DoDamage(211),
    /**
     * <pre>
     *兵的路线
     * </pre>
     *
     * <code>MsgID_War_SoldierRoute = 212;</code>
     */
    MsgID_War_SoldierRoute(212),
    /**
     * <pre>
     *属性更新(包含血量更新全都用这个接口)
     * </pre>
     *
     * <code>MsgID_War_AttributeUpdate = 213;</code>
     */
    MsgID_War_AttributeUpdate(213),
    /**
     * <pre>
     *准备开始战斗
     * </pre>
     *
     * <code>MsgID_War_ReadyStart = 214;</code>
     */
    MsgID_War_ReadyStart(214),
    /**
     * <pre>
     *同步BUFF
     * </pre>
     *
     * <code>MsgID_War_SynBuff = 215;</code>
     */
    MsgID_War_SynBuff(215),
    /**
     * <pre>
     *同步倒计时
     * </pre>
     *
     * <code>MsgID_War_SynCountDown = 216;</code>
     */
    MsgID_War_SynCountDown(216),
    /**
     * <pre>
     *投降
     * </pre>
     *
     * <code>MsgID_War_Surrender = 217;</code>
     */
    MsgID_War_Surrender(217),
    /**
     * <pre>
     *自动战斗
     * </pre>
     *
     * <code>MsgID_War_AutoBattle = 218;</code>
     */
    MsgID_War_AutoBattle(218),
    /**
     * <pre>
     *暂停
     * </pre>
     *
     * <code>MsgID_War_Pause = 219;</code>
     */
    MsgID_War_Pause(219),
    /**
     * <pre>
     *查看玩家信息
     * </pre>
     *
     * <code>MsgID_Player_GetInfo = 301;</code>
     */
    MsgID_Player_GetInfo(301),
    /**
     * <pre>
     *刷新一些重要数据(比如积分,金币)
     * </pre>
     *
     * <code>MsgID_Player_FlushData = 302;</code>
     */
    MsgID_Player_FlushData(302),
    /**
     * <pre>
     *红点消息提示
     * </pre>
     *
     * <code>MsgID_Player_RedPointRemind = 303;</code>
     */
    MsgID_Player_RedPointRemind(303),
    /**
     * <pre>
     *同步基本数据，总集
     * </pre>
     *
     * <code>MsgID_Player_SynBaseData = 304;</code>
     */
    MsgID_Player_SynBaseData(304),
    /**
     * <pre>
     *匹配对手
     * </pre>
     *
     * <code>MsgID_Player_ArenaMatch = 305;</code>
     */
    MsgID_Player_ArenaMatch(305),
    /**
     * <pre>
     *取消匹配
     * </pre>
     *
     * <code>MsgID_Player_CancelArenaMatch = 306;</code>
     */
    MsgID_Player_CancelArenaMatch(306),
    /**
     * <pre>
     *修改名字
     * </pre>
     *
     * <code>MsgID_Player_EditPlayerName = 307;</code>
     */
    MsgID_Player_EditPlayerName(307),
    /**
     * <pre>
     *修改头像
     * </pre>
     *
     * <code>MsgID_Player_EditPlayerAvatar = 308;</code>
     */
    MsgID_Player_EditPlayerAvatar(308),
    /**
     * <pre>
     *改变消费提醒的状态
     * </pre>
     *
     * <code>MsgID_Player_ChangeConsumeRemindStatus = 309;</code>
     */
    MsgID_Player_ChangeConsumeRemindStatus(309),
    /**
     * <pre>
     *改变上阵技能
     * </pre>
     *
     * <code>MsgID_Player_ChangeEquippedSkill = 310;</code>
     */
    MsgID_Player_ChangeEquippedSkill(310),
    /**
     * <pre>
     *用户设置面板初始化信息
     * </pre>
     *
     * <code>MsgID_Player_SettingBoardInit = 311;</code>
     */
    MsgID_Player_SettingBoardInit(311),
    /**
     * <pre>
     *刷新获得物品
     * </pre>
     *
     * <code>MsgID_Player_FlushGoodsGet = 312;</code>
     */
    MsgID_Player_FlushGoodsGet(312),
    /**
     * <pre>
     *获取副本剩余挑战次数
     * </pre>
     *
     * <code>MsgID_Player_GetInstanceRemainChallengeTime = 313;</code>
     */
    MsgID_Player_GetInstanceRemainChallengeTime(313),
    /**
     * <pre>
     *更新引导进度
     * </pre>
     *
     * <code>MsgID_Player_UpdateGuideProgress = 314;</code>
     */
    MsgID_Player_UpdateGuideProgress(314),
    /**
     * <pre>
     *获取验证码
     * </pre>
     *
     * <code>MsgID_Player_GetMobileCaptcha = 315;</code>
     */
    MsgID_Player_GetMobileCaptcha(315),
    /**
     * <pre>
     *绑定手机号
     * </pre>
     *
     * <code>MsgID_Player_BindingMobile = 316;</code>
     */
    MsgID_Player_BindingMobile(316),
    /**
     * <pre>
     *cdk使用
     * </pre>
     *
     * <code>MsgID_Player_CdkUse = 317;</code>
     */
    MsgID_Player_CdkUse(317),
    /**
     * <pre>
     *意见反馈
     * </pre>
     *
     * <code>MsgID_Player_FeedBack = 318;</code>
     */
    MsgID_Player_FeedBack(318),
    /**
     * <pre>
     *排行榜
     * </pre>
     *
     * <code>MsgID_Player_RankList = 319;</code>
     */
    MsgID_Player_RankList(319),
    /**
     * <pre>
     *进入主城场景
     * </pre>
     *
     * <code>MsgID_Map_EnterHomeScene = 401;</code>
     */
    MsgID_Map_EnterHomeScene(401),
    /**
     * <pre>
     *添加建筑构建队列
     * </pre>
     *
     * <code>MsgID_Map_AddBuildingQueue = 402;</code>
     */
    MsgID_Map_AddBuildingQueue(402),
    /**
     * <pre>
     *移除建筑构建队列
     * </pre>
     *
     * <code>MsgID_Map_RemoveBuildingQueue = 403;</code>
     */
    MsgID_Map_RemoveBuildingQueue(403),
    /**
     * <pre>
     *建筑构建完成
     * </pre>
     *
     * <code>MsgID_Map_BuildingFinished = 404;</code>
     */
    MsgID_Map_BuildingFinished(404),
    /**
     * <pre>
     *建筑升级
     * </pre>
     *
     * <code>MsgID_Map_BuildingLevelUp = 405;</code>
     */
    MsgID_Map_BuildingLevelUp(405),
    /**
     * <pre>
     *搬家
     * </pre>
     *
     * <code>MsgID_Map_MoveHome = 406;</code>
     */
    MsgID_Map_MoveHome(406),
    /**
     * <pre>
     *兵种配置
     * </pre>
     *
     * <code>MsgID_Bag_SoldierTeamConfig = 501;</code>
     */
    MsgID_Bag_SoldierTeamConfig(501),
    /**
     * <pre>
     *出战队伍选择
     * </pre>
     *
     * <code>MsgID_Bag_SoldierTeamBattle = 502;</code>
     */
    MsgID_Bag_SoldierTeamBattle(502),
    /**
     * <pre>
     *兵种升级
     * </pre>
     *
     * <code>MsgID_Bag_CardLevelUp = 503;</code>
     */
    MsgID_Bag_CardLevelUp(503),
    /**
     * <pre>
     *我的卡包
     * </pre>
     *
     * <code>MsgID_Bag_MyCard = 504;</code>
     */
    MsgID_Bag_MyCard(504),
    /**
     * <pre>
     *我的卡组
     * </pre>
     *
     * <code>MsgID_Bag_MyCardTeam = 505;</code>
     */
    MsgID_Bag_MyCardTeam(505),
    /**
     * <pre>
     *设置出战卡组
     * </pre>
     *
     * <code>MsgID_Bag_SetBattleCardTeam = 506;</code>
     */
    MsgID_Bag_SetBattleCardTeam(506),
    /**
     * <pre>
     *卡片替换
     * </pre>
     *
     * <code>MsgID_Bag_SetCardReplace = 507;</code>
     */
    MsgID_Bag_SetCardReplace(507),
    /**
     * <pre>
     *卡牌详情
     * </pre>
     *
     * <code>MsgID_Bag_CardDetail = 508;</code>
     */
    MsgID_Bag_CardDetail(508),
    /**
     * <pre>
     *卡牌升级 
     * </pre>
     *
     * <code>MsgID_Bag_CardUpLv = 509;</code>
     */
    MsgID_Bag_CardUpLv(509),
    /**
     * <pre>
     *卡牌升星
     * </pre>
     *
     * <code>MsgID_Bag_CardUpStar = 510;</code>
     */
    MsgID_Bag_CardUpStar(510),
    /**
     * <pre>
     *卡牌宿命
     * </pre>
     *
     * <code>MsgID_Bag_CardFate = 511;</code>
     */
    MsgID_Bag_CardFate(511),
    /**
     * <pre>
     *卡牌宿命列表
     * </pre>
     *
     * <code>MsgID_Bag_CardFateList = 512;</code>
     */
    MsgID_Bag_CardFateList(512),
    /**
     * <pre>
     *装备强化
     * </pre>
     *
     * <code>MsgID_Bag_EquipIntensify = 513;</code>
     */
    MsgID_Bag_EquipIntensify(513),
    /**
     * <pre>
     *装备合成
     * </pre>
     *
     * <code>MsgID_Bag_EquipUp = 514;</code>
     */
    MsgID_Bag_EquipUp(514),
    /**
     * <pre>
     *饰品进阶
     * </pre>
     *
     * <code>MsgID_Bag_AccessoryUp = 515;</code>
     */
    MsgID_Bag_AccessoryUp(515),
    /**
     * <pre>
     *饰品强化
     * </pre>
     *
     * <code>MsgID_Bag_AccessoryIntensify = 516;</code>
     */
    MsgID_Bag_AccessoryIntensify(516),
    /**
     * <pre>
     *经验卷轴添加经验
     * </pre>
     *
     * <code>MsgID_Bag_CardAddExp = 517;</code>
     */
    MsgID_Bag_CardAddExp(517),
    /**
     * <pre>
     *饰品强化经验卷轴升级
     * </pre>
     *
     * <code>MsgID_Bag_AccessoryAddExp = 518;</code>
     */
    MsgID_Bag_AccessoryAddExp(518),
    /**
     * <pre>
     *卡牌合成
     * </pre>
     *
     * <code>MsgID_Bag_CardSyn = 519;</code>
     */
    MsgID_Bag_CardSyn(519),
    /**
     * <pre>
     *卡片重生
     * </pre>
     *
     * <code>MsgID_Bag_RebirthCard = 520;</code>
     */
    MsgID_Bag_RebirthCard(520),
    /**
     * <pre>
     *英魂分解可分解卡牌预览
     * </pre>
     *
     * <code>MsgID_Bag_ResolveCardPreview = 521;</code>
     */
    MsgID_Bag_ResolveCardPreview(521),
    /**
     * <pre>
     *英魂分解
     * </pre>
     *
     * <code>MsgID_Bag_SoulResolve = 522;</code>
     */
    MsgID_Bag_SoulResolve(522),
    /**
     * <pre>
     *装备碎片分解
     * </pre>
     *
     * <code>MsgID_Bag_EquipResolve = 523;</code>
     */
    MsgID_Bag_EquipResolve(523),
    /**
     * <pre>
     *卡牌在战斗卡组下阵
     * </pre>
     *
     * <code>MsgID_Bag_QuitBattleGroup = 524;</code>
     */
    MsgID_Bag_QuitBattleGroup(524),
    /**
     * <pre>
     *道具使用
     * </pre>
     *
     * <code>MsgID_Bag_UseProp = 525;</code>
     */
    MsgID_Bag_UseProp(525),
    /**
     * <pre>
     *饰品激活
     * </pre>
     *
     * <code>MsgID_Bag_AccessoryActivated = 526;</code>
     */
    MsgID_Bag_AccessoryActivated(526),
    /**
     * <pre>
     *上阵卡片替换
     * </pre>
     *
     * <code>MsgID_Bag_BattleCardReset = 527;</code>
     */
    MsgID_Bag_BattleCardReset(527),
    /**
     * <pre>
     *查看副本进度信息
     * </pre>
     *
     * <code>MsgID_Instance_GetInstanceInfo = 601;</code>
     */
    MsgID_Instance_GetInstanceInfo(601),
    /**
     * <pre>
     *通过某一副本关卡
     * </pre>
     *
     * <code>MsgID_Instance_PassLevel = 602;</code>
     */
    MsgID_Instance_PassLevel(602),
    /**
     * <pre>
     *领取副本奖励
     * </pre>
     *
     * <code>MsgID_Instance_ReceiveAward = 603;</code>
     */
    MsgID_Instance_ReceiveAward(603),
    /**
     * <pre>
     *副本挑战发起
     * </pre>
     *
     * <code>MsgID_Instance_RequestLevelBattle = 604;</code>
     */
    MsgID_Instance_RequestLevelBattle(604),
    /**
     * <pre>
     *领取关卡宝箱奖励
     * </pre>
     *
     * <code>MsgID_Instance_ReceiveLevelBoxReward = 605;</code>
     */
    MsgID_Instance_ReceiveLevelBoxReward(605),
    /**
     * <pre>
     *获取最后一次的战斗信息
     * </pre>
     *
     * <code>MsgID_Instance_GetLastPassLevel = 606;</code>
     */
    MsgID_Instance_GetLastPassLevel(606),
    /**
     * <pre>
     *查看竞技场信息
     * </pre>
     *
     * <code>MsgID_Arena_GetArenaInfo = 701;</code>
     */
    MsgID_Arena_GetArenaInfo(701),
    /**
     * <pre>
     *竞技场挑战
     * </pre>
     *
     * <code>MsgID_Arena_Challenge = 702;</code>
     */
    MsgID_Arena_Challenge(702),
    /**
     * <pre>
     *竞技场每日领取奖励
     * </pre>
     *
     * <code>MsgID_Arena_GetDailyReward = 703;</code>
     */
    MsgID_Arena_GetDailyReward(703),
    /**
     * <pre>
     *竞技场查看排行
     * </pre>
     *
     * <code>MsgID_Arena_PreviewRank = 704;</code>
     */
    MsgID_Arena_PreviewRank(704),
    /**
     * <pre>
     *兑换竞技场商店奖励
     * </pre>
     *
     * <code>MsgID_Arena_ExchangeReward = 705;</code>
     */
    MsgID_Arena_ExchangeReward(705),
    /**
     * <pre>
     *竞技场兑换记录
     * </pre>
     *
     * <code>MsgID_Arena_RewardRecord = 706;</code>
     */
    MsgID_Arena_RewardRecord(706),
    /**
     * <pre>
     *竞技场副本扫荡
     * </pre>
     *
     * <code>MsgID_Arena_Sweep = 707;</code>
     */
    MsgID_Arena_Sweep(707),
    /**
     * <pre>
     *抽奖
     * </pre>
     *
     * <code>MsgID_Pub_LotteryClick = 801;</code>
     */
    MsgID_Pub_LotteryClick(801),
    /**
     * <pre>
     *初始化
     * </pre>
     *
     * <code>MsgID_Pub_LotteryInit = 802;</code>
     */
    MsgID_Pub_LotteryInit(802),
    /**
     * <pre>
     *祭坛初始化
     * </pre>
     *
     * <code>MsgID_Altar_Init = 901;</code>
     */
    MsgID_Altar_Init(901),
    /**
     * <pre>
     *祭祀
     * </pre>
     *
     * <code>MsgID_Altar_Sacrifice = 902;</code>
     */
    MsgID_Altar_Sacrifice(902),
    /**
     * <pre>
     *初始化页面信息
     * </pre>
     *
     * <code>MsgID_OfficialWar_InitInfo = 1001;</code>
     */
    MsgID_OfficialWar_InitInfo(1001),
    /**
     * <pre>
     *查看官阶对应的人员
     * </pre>
     *
     * <code>MsgID_OfficialWar_PreviewRank = 1002;</code>
     */
    MsgID_OfficialWar_PreviewRank(1002),
    /**
     * <pre>
     *挑战对应官阶
     * </pre>
     *
     * <code>MsgID_OfficialWar_ChallengeRank = 1003;</code>
     */
    MsgID_OfficialWar_ChallengeRank(1003),
    /**
     * <pre>
     *扫荡对应官阶
     * </pre>
     *
     * <code>MsgID_OfficialWar_SweepRank = 1004;</code>
     */
    MsgID_OfficialWar_SweepRank(1004),
    /**
     * <pre>
     *每日领取奖励
     * </pre>
     *
     * <code>MsgID_OfficialWar_GetDailyReward = 1005;</code>
     */
    MsgID_OfficialWar_GetDailyReward(1005),
    /**
     * <pre>
     *兑换商店奖励
     * </pre>
     *
     * <code>MsgID_OfficialWar_ExchangeReward = 1006;</code>
     */
    MsgID_OfficialWar_ExchangeReward(1006),
    /**
     * <pre>
     *兑换记录
     * </pre>
     *
     * <code>MsgID_OfficialWar_RewardRecord = 1007;</code>
     */
    MsgID_OfficialWar_RewardRecord(1007),
    /**
     * <pre>
     *积分兑换
     * </pre>
     *
     * <code>MsgID_OfficialWar_IntegralReward = 1008;</code>
     */
    MsgID_OfficialWar_IntegralReward(1008),
    /**
     * <pre>
     *积分兑换记录
     * </pre>
     *
     * <code>MsgID_OfficialWar_IntegralRewardRecord = 1009;</code>
     */
    MsgID_OfficialWar_IntegralRewardRecord(1009),
    /**
     * <pre>
     *发起挑战
     * </pre>
     *
     * <code>MsgID_OfficialWar_RequestBattle = 1010;</code>
     */
    MsgID_OfficialWar_RequestBattle(1010),
    /**
     * <pre>
     *任务列表显示
     * </pre>
     *
     * <code>MsgID_Task_TaskList = 1101;</code>
     */
    MsgID_Task_TaskList(1101),
    /**
     * <pre>
     *任务领奖
     * </pre>
     *
     * <code>MsgID_Task_TaskReward = 1102;</code>
     */
    MsgID_Task_TaskReward(1102),
    /**
     * <pre>
     *宝箱领奖
     * </pre>
     *
     * <code>MsgID_Task_TreasureReward = 1103;</code>
     */
    MsgID_Task_TreasureReward(1103),
    /**
     * <pre>
     *主线任务完成推送
     * </pre>
     *
     * <code>MsgID_Task_TaskMainDoneNotify = 1104;</code>
     */
    MsgID_Task_TaskMainDoneNotify(1104),
    /**
     * <pre>
     *商店初始化（包含刷新）
     * </pre>
     *
     * <code>MsgID_Store_InitInfo = 1201;</code>
     */
    MsgID_Store_InitInfo(1201),
    /**
     * <pre>
     *商店购买
     * </pre>
     *
     * <code>MsgID_Store_BuyGoods = 1202;</code>
     */
    MsgID_Store_BuyGoods(1202),
    /**
     * <pre>
     *次数购买(包含各类挑战，刷新次数)
     * </pre>
     *
     * <code>MsgID_Store_BuyTimes = 1203;</code>
     */
    MsgID_Store_BuyTimes(1203),
    /**
     * <pre>
     *英雄圣殿初始化页面信息
     * </pre>
     *
     * <code>MsgID_HeroTemple_InitInfo = 1301;</code>
     */
    MsgID_HeroTemple_InitInfo(1301),
    /**
     * <pre>
     *英雄圣殿挑战
     * </pre>
     *
     * <code>MsgID_HeroTemple_Challenge = 1302;</code>
     */
    MsgID_HeroTemple_Challenge(1302),
    /**
     * <pre>
     *英雄圣殿扫荡
     * </pre>
     *
     * <code>MsgID_HeroTemple_Sweep = 1303;</code>
     */
    MsgID_HeroTemple_Sweep(1303),
    /**
     * <pre>
     *邮件列表
     * </pre>
     *
     * <code>MsgID_Mail_List = 1401;</code>
     */
    MsgID_Mail_List(1401),
    /**
     * <pre>
     *邮件详情
     * </pre>
     *
     * <code>MsgID_Mail_Detail = 1402;</code>
     */
    MsgID_Mail_Detail(1402),
    /**
     * <pre>
     *领取附件
     * </pre>
     *
     * <code>MsgID_Mail_GetAuxiliary = 1403;</code>
     */
    MsgID_Mail_GetAuxiliary(1403),
    /**
     * <pre>
     *私信列表
     * </pre>
     *
     * <code>MsgID_Mail_PrivacyMailList = 1404;</code>
     */
    MsgID_Mail_PrivacyMailList(1404),
    /**
     * <pre>
     *私信详情
     * </pre>
     *
     * <code>MsgID_Mail_PrivacyMailDetail = 1405;</code>
     */
    MsgID_Mail_PrivacyMailDetail(1405),
    /**
     * <pre>
     *发送回复私信
     * </pre>
     *
     * <code>MsgID_Mail_SendPrivacyMail = 1406;</code>
     */
    MsgID_Mail_SendPrivacyMail(1406),
    /**
     * <pre>
     *黑名单列表
     * </pre>
     *
     * <code>MsgID_Mail_BlackList = 1407;</code>
     */
    MsgID_Mail_BlackList(1407),
    /**
     * <pre>
     *添加移除黑名单
     * </pre>
     *
     * <code>MsgID_Mail_AddAndRemoveBlackList = 1408;</code>
     */
    MsgID_Mail_AddAndRemoveBlackList(1408),
    /**
     * <pre>
     *检测是否具有全员发送权限
     * </pre>
     *
     * <code>MsgID_Mail_CheckSendJurisdiction = 1409;</code>
     */
    MsgID_Mail_CheckSendJurisdiction(1409),
    /**
     * <pre>
     *新邮件推送
     * </pre>
     *
     * <code>MsgID_Mail_NewMailNotify = 1410;</code>
     */
    MsgID_Mail_NewMailNotify(1410),
    /**
     * <pre>
     *充值初始化
     * </pre>
     *
     * <code>MsgID_Bonus_RechargeInit = 1501;</code>
     */
    MsgID_Bonus_RechargeInit(1501),
    /**
     * <pre>
     *充值结果回调
     * </pre>
     *
     * <code>MsgID_Bonus_RechargeResult = 1502;</code>
     */
    MsgID_Bonus_RechargeResult(1502),
    /**
     * <pre>
     *购买vip礼包
     * </pre>
     *
     * <code>MsgID_Bonus_BuyVipGiftBag = 1503;</code>
     */
    MsgID_Bonus_BuyVipGiftBag(1503),
    /**
     * <pre>
     *领取月卡奖励
     * </pre>
     *
     * <code>MsgID_Bonus_ReceiveMouthCardReward = 1504;</code>
     */
    MsgID_Bonus_ReceiveMouthCardReward(1504),
    /**
     * <pre>
     *领取首冲礼包
     * </pre>
     *
     * <code>MsgID_Bonus_ReceiveFirstRechargeReward = 1505;</code>
     */
    MsgID_Bonus_ReceiveFirstRechargeReward(1505),
    /**
     * <pre>
     *福利面板初始化
     * </pre>
     *
     * <code>MsgID_Bonus_BonusBoardInit = 1506;</code>
     */
    MsgID_Bonus_BonusBoardInit(1506),
    /**
     * <pre>
     *每日签到
     * </pre>
     *
     * <code>MsgID_Bonus_DailySignReward = 1507;</code>
     */
    MsgID_Bonus_DailySignReward(1507),
    /**
     * <pre>
     *购买基金
     * </pre>
     *
     * <code>MsgID_Bonus_BuyFund = 1508;</code>
     */
    MsgID_Bonus_BuyFund(1508),
    /**
     * <pre>
     *领取基金奖励
     * </pre>
     *
     * <code>MsgID_Bonus_ReceiveFundReward = 1509;</code>
     */
    MsgID_Bonus_ReceiveFundReward(1509),
    /**
     * <pre>
     *累计登陆奖励初始化
     * </pre>
     *
     * <code>MsgID_Bonus_LoginTimesRewardInit = 1510;</code>
     */
    MsgID_Bonus_LoginTimesRewardInit(1510),
    /**
     * <pre>
     *累计登陆奖励领取
     * </pre>
     *
     * <code>MsgID_Bonus_ReceiveLoginTimesReward = 1511;</code>
     */
    MsgID_Bonus_ReceiveLoginTimesReward(1511),
    /**
     * <pre>
     *充值检测
     * </pre>
     *
     * <code>MsgID_Bonus_RechargeCheck = 1512;</code>
     */
    MsgID_Bonus_RechargeCheck(1512),
    /**
     * <pre>
     *远征初始化
     * </pre>
     *
     * <code>MsgID_Expedition_Init = 1601;</code>
     */
    MsgID_Expedition_Init(1601),
    /**
     * <pre>
     *远征挑战发起
     * </pre>
     *
     * <code>MsgID_Expedition_ChallengeRequest = 1602;</code>
     */
    MsgID_Expedition_ChallengeRequest(1602),
    /**
     * <pre>
     *远征刷新boss
     * </pre>
     *
     * <code>MsgID_Expedition_FreshBoss = 1603;</code>
     */
    MsgID_Expedition_FreshBoss(1603),
    /**
     * <pre>
     *远征召唤boss
     * </pre>
     *
     * <code>MsgID_Expedition_CallBoss = 1604;</code>
     */
    MsgID_Expedition_CallBoss(1604),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *不使用,proto3枚举首项值必为0
     * </pre>
     *
     * <code>MsgID_NeverUse = 0;</code>
     */
    public static final int MsgID_NeverUse_VALUE = 0;
    /**
     * <pre>
     *注册
     * </pre>
     *
     * <code>MsgID_System_Regist = 101;</code>
     */
    public static final int MsgID_System_Regist_VALUE = 101;
    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>MsgID_System_Login = 102;</code>
     */
    public static final int MsgID_System_Login_VALUE = 102;
    /**
     * <pre>
     *心跳检测
     * </pre>
     *
     * <code>MsgID_System_Ping = 103;</code>
     */
    public static final int MsgID_System_Ping_VALUE = 103;
    /**
     * <pre>
     *获取验证码
     * </pre>
     *
     * <code>MsgID_System_GetCaptcha = 104;</code>
     */
    public static final int MsgID_System_GetCaptcha_VALUE = 104;
    /**
     * <pre>
     *统一的一个通知消息
     * </pre>
     *
     * <code>MsgID_System_NotifyAlert = 105;</code>
     */
    public static final int MsgID_System_NotifyAlert_VALUE = 105;
    /**
     * <pre>
     *退出登录
     * </pre>
     *
     * <code>MsgID_System_Logout = 106;</code>
     */
    public static final int MsgID_System_Logout_VALUE = 106;
    /**
     * <pre>
     *登录,开发用
     * </pre>
     *
     * <code>MsgID_System_SuperLogin = 199;</code>
     */
    public static final int MsgID_System_SuperLogin_VALUE = 199;
    /**
     * <pre>
     *战斗服务器重连
     * </pre>
     *
     * <code>MsgID_System_BattleReconnect = 110;</code>
     */
    public static final int MsgID_System_BattleReconnect_VALUE = 110;
    /**
     * <pre>
     *cmd
     * </pre>
     *
     * <code>MsgID_System_GMCmd = 111;</code>
     */
    public static final int MsgID_System_GMCmd_VALUE = 111;
    /**
     * <pre>
     *顶号
     * </pre>
     *
     * <code>MsgID_System_LoginOtherPlace = 112;</code>
     */
    public static final int MsgID_System_LoginOtherPlace_VALUE = 112;
    /**
     * <pre>
     *取消等待
     * </pre>
     *
     * <code>MsgID_System_CancelWait = 113;</code>
     */
    public static final int MsgID_System_CancelWait_VALUE = 113;
    /**
     * <pre>
     *因为某些原因离线了,通知客户端
     * </pre>
     *
     * <code>MsgID_System_Offline = 114;</code>
     */
    public static final int MsgID_System_Offline_VALUE = 114;
    /**
     * <pre>
     *创建战斗
     * </pre>
     *
     * <code>MsgID_War_Create = 201;</code>
     */
    public static final int MsgID_War_Create_VALUE = 201;
    /**
     * <pre>
     *上战场(卡牌放出去)
     * </pre>
     *
     * <code>MsgID_War_ToBattle = 202;</code>
     */
    public static final int MsgID_War_ToBattle_VALUE = 202;
    /**
     * <pre>
     *敌对的兵相遇了，要开战了
     * </pre>
     *
     * <code>MsgID_War_SoldierBattleStart = 203;</code>
     */
    public static final int MsgID_War_SoldierBattleStart_VALUE = 203;
    /**
     * <pre>
     *战斗结果
     * </pre>
     *
     * <code>MsgID_War_SynResult = 204;</code>
     */
    public static final int MsgID_War_SynResult_VALUE = 204;
    /**
     * <pre>
     *使用技能
     * </pre>
     *
     * <code>MsgID_War_UseSkill = 205;</code>
     */
    public static final int MsgID_War_UseSkill_VALUE = 205;
    /**
     * <pre>
     *添加效果
     * </pre>
     *
     * <code>MsgID_War_AddEffect = 206;</code>
     */
    public static final int MsgID_War_AddEffect_VALUE = 206;
    /**
     * <pre>
     *移除效果
     * </pre>
     *
     * <code>MsgID_War_RemoveEffect = 207;</code>
     */
    public static final int MsgID_War_RemoveEffect_VALUE = 207;
    /**
     * <pre>
     *刷新效果剩余持续时间
     * </pre>
     *
     * <code>MsgID_War_UpdateEffectDuration = 208;</code>
     */
    public static final int MsgID_War_UpdateEffectDuration_VALUE = 208;
    /**
     * <pre>
     *对象死亡
     * </pre>
     *
     * <code>MsgID_War_ObjectDie = 209;</code>
     */
    public static final int MsgID_War_ObjectDie_VALUE = 209;
    /**
     * <pre>
     *同步位置
     * </pre>
     *
     * <code>MsgID_War_SynPos = 210;</code>
     */
    public static final int MsgID_War_SynPos_VALUE = 210;
    /**
     * <pre>
     *伤害同步
     * </pre>
     *
     * <code>MsgID_War_DoDamage = 211;</code>
     */
    public static final int MsgID_War_DoDamage_VALUE = 211;
    /**
     * <pre>
     *兵的路线
     * </pre>
     *
     * <code>MsgID_War_SoldierRoute = 212;</code>
     */
    public static final int MsgID_War_SoldierRoute_VALUE = 212;
    /**
     * <pre>
     *属性更新(包含血量更新全都用这个接口)
     * </pre>
     *
     * <code>MsgID_War_AttributeUpdate = 213;</code>
     */
    public static final int MsgID_War_AttributeUpdate_VALUE = 213;
    /**
     * <pre>
     *准备开始战斗
     * </pre>
     *
     * <code>MsgID_War_ReadyStart = 214;</code>
     */
    public static final int MsgID_War_ReadyStart_VALUE = 214;
    /**
     * <pre>
     *同步BUFF
     * </pre>
     *
     * <code>MsgID_War_SynBuff = 215;</code>
     */
    public static final int MsgID_War_SynBuff_VALUE = 215;
    /**
     * <pre>
     *同步倒计时
     * </pre>
     *
     * <code>MsgID_War_SynCountDown = 216;</code>
     */
    public static final int MsgID_War_SynCountDown_VALUE = 216;
    /**
     * <pre>
     *投降
     * </pre>
     *
     * <code>MsgID_War_Surrender = 217;</code>
     */
    public static final int MsgID_War_Surrender_VALUE = 217;
    /**
     * <pre>
     *自动战斗
     * </pre>
     *
     * <code>MsgID_War_AutoBattle = 218;</code>
     */
    public static final int MsgID_War_AutoBattle_VALUE = 218;
    /**
     * <pre>
     *暂停
     * </pre>
     *
     * <code>MsgID_War_Pause = 219;</code>
     */
    public static final int MsgID_War_Pause_VALUE = 219;
    /**
     * <pre>
     *查看玩家信息
     * </pre>
     *
     * <code>MsgID_Player_GetInfo = 301;</code>
     */
    public static final int MsgID_Player_GetInfo_VALUE = 301;
    /**
     * <pre>
     *刷新一些重要数据(比如积分,金币)
     * </pre>
     *
     * <code>MsgID_Player_FlushData = 302;</code>
     */
    public static final int MsgID_Player_FlushData_VALUE = 302;
    /**
     * <pre>
     *红点消息提示
     * </pre>
     *
     * <code>MsgID_Player_RedPointRemind = 303;</code>
     */
    public static final int MsgID_Player_RedPointRemind_VALUE = 303;
    /**
     * <pre>
     *同步基本数据，总集
     * </pre>
     *
     * <code>MsgID_Player_SynBaseData = 304;</code>
     */
    public static final int MsgID_Player_SynBaseData_VALUE = 304;
    /**
     * <pre>
     *匹配对手
     * </pre>
     *
     * <code>MsgID_Player_ArenaMatch = 305;</code>
     */
    public static final int MsgID_Player_ArenaMatch_VALUE = 305;
    /**
     * <pre>
     *取消匹配
     * </pre>
     *
     * <code>MsgID_Player_CancelArenaMatch = 306;</code>
     */
    public static final int MsgID_Player_CancelArenaMatch_VALUE = 306;
    /**
     * <pre>
     *修改名字
     * </pre>
     *
     * <code>MsgID_Player_EditPlayerName = 307;</code>
     */
    public static final int MsgID_Player_EditPlayerName_VALUE = 307;
    /**
     * <pre>
     *修改头像
     * </pre>
     *
     * <code>MsgID_Player_EditPlayerAvatar = 308;</code>
     */
    public static final int MsgID_Player_EditPlayerAvatar_VALUE = 308;
    /**
     * <pre>
     *改变消费提醒的状态
     * </pre>
     *
     * <code>MsgID_Player_ChangeConsumeRemindStatus = 309;</code>
     */
    public static final int MsgID_Player_ChangeConsumeRemindStatus_VALUE = 309;
    /**
     * <pre>
     *改变上阵技能
     * </pre>
     *
     * <code>MsgID_Player_ChangeEquippedSkill = 310;</code>
     */
    public static final int MsgID_Player_ChangeEquippedSkill_VALUE = 310;
    /**
     * <pre>
     *用户设置面板初始化信息
     * </pre>
     *
     * <code>MsgID_Player_SettingBoardInit = 311;</code>
     */
    public static final int MsgID_Player_SettingBoardInit_VALUE = 311;
    /**
     * <pre>
     *刷新获得物品
     * </pre>
     *
     * <code>MsgID_Player_FlushGoodsGet = 312;</code>
     */
    public static final int MsgID_Player_FlushGoodsGet_VALUE = 312;
    /**
     * <pre>
     *获取副本剩余挑战次数
     * </pre>
     *
     * <code>MsgID_Player_GetInstanceRemainChallengeTime = 313;</code>
     */
    public static final int MsgID_Player_GetInstanceRemainChallengeTime_VALUE = 313;
    /**
     * <pre>
     *更新引导进度
     * </pre>
     *
     * <code>MsgID_Player_UpdateGuideProgress = 314;</code>
     */
    public static final int MsgID_Player_UpdateGuideProgress_VALUE = 314;
    /**
     * <pre>
     *获取验证码
     * </pre>
     *
     * <code>MsgID_Player_GetMobileCaptcha = 315;</code>
     */
    public static final int MsgID_Player_GetMobileCaptcha_VALUE = 315;
    /**
     * <pre>
     *绑定手机号
     * </pre>
     *
     * <code>MsgID_Player_BindingMobile = 316;</code>
     */
    public static final int MsgID_Player_BindingMobile_VALUE = 316;
    /**
     * <pre>
     *cdk使用
     * </pre>
     *
     * <code>MsgID_Player_CdkUse = 317;</code>
     */
    public static final int MsgID_Player_CdkUse_VALUE = 317;
    /**
     * <pre>
     *意见反馈
     * </pre>
     *
     * <code>MsgID_Player_FeedBack = 318;</code>
     */
    public static final int MsgID_Player_FeedBack_VALUE = 318;
    /**
     * <pre>
     *排行榜
     * </pre>
     *
     * <code>MsgID_Player_RankList = 319;</code>
     */
    public static final int MsgID_Player_RankList_VALUE = 319;
    /**
     * <pre>
     *进入主城场景
     * </pre>
     *
     * <code>MsgID_Map_EnterHomeScene = 401;</code>
     */
    public static final int MsgID_Map_EnterHomeScene_VALUE = 401;
    /**
     * <pre>
     *添加建筑构建队列
     * </pre>
     *
     * <code>MsgID_Map_AddBuildingQueue = 402;</code>
     */
    public static final int MsgID_Map_AddBuildingQueue_VALUE = 402;
    /**
     * <pre>
     *移除建筑构建队列
     * </pre>
     *
     * <code>MsgID_Map_RemoveBuildingQueue = 403;</code>
     */
    public static final int MsgID_Map_RemoveBuildingQueue_VALUE = 403;
    /**
     * <pre>
     *建筑构建完成
     * </pre>
     *
     * <code>MsgID_Map_BuildingFinished = 404;</code>
     */
    public static final int MsgID_Map_BuildingFinished_VALUE = 404;
    /**
     * <pre>
     *建筑升级
     * </pre>
     *
     * <code>MsgID_Map_BuildingLevelUp = 405;</code>
     */
    public static final int MsgID_Map_BuildingLevelUp_VALUE = 405;
    /**
     * <pre>
     *搬家
     * </pre>
     *
     * <code>MsgID_Map_MoveHome = 406;</code>
     */
    public static final int MsgID_Map_MoveHome_VALUE = 406;
    /**
     * <pre>
     *兵种配置
     * </pre>
     *
     * <code>MsgID_Bag_SoldierTeamConfig = 501;</code>
     */
    public static final int MsgID_Bag_SoldierTeamConfig_VALUE = 501;
    /**
     * <pre>
     *出战队伍选择
     * </pre>
     *
     * <code>MsgID_Bag_SoldierTeamBattle = 502;</code>
     */
    public static final int MsgID_Bag_SoldierTeamBattle_VALUE = 502;
    /**
     * <pre>
     *兵种升级
     * </pre>
     *
     * <code>MsgID_Bag_CardLevelUp = 503;</code>
     */
    public static final int MsgID_Bag_CardLevelUp_VALUE = 503;
    /**
     * <pre>
     *我的卡包
     * </pre>
     *
     * <code>MsgID_Bag_MyCard = 504;</code>
     */
    public static final int MsgID_Bag_MyCard_VALUE = 504;
    /**
     * <pre>
     *我的卡组
     * </pre>
     *
     * <code>MsgID_Bag_MyCardTeam = 505;</code>
     */
    public static final int MsgID_Bag_MyCardTeam_VALUE = 505;
    /**
     * <pre>
     *设置出战卡组
     * </pre>
     *
     * <code>MsgID_Bag_SetBattleCardTeam = 506;</code>
     */
    public static final int MsgID_Bag_SetBattleCardTeam_VALUE = 506;
    /**
     * <pre>
     *卡片替换
     * </pre>
     *
     * <code>MsgID_Bag_SetCardReplace = 507;</code>
     */
    public static final int MsgID_Bag_SetCardReplace_VALUE = 507;
    /**
     * <pre>
     *卡牌详情
     * </pre>
     *
     * <code>MsgID_Bag_CardDetail = 508;</code>
     */
    public static final int MsgID_Bag_CardDetail_VALUE = 508;
    /**
     * <pre>
     *卡牌升级 
     * </pre>
     *
     * <code>MsgID_Bag_CardUpLv = 509;</code>
     */
    public static final int MsgID_Bag_CardUpLv_VALUE = 509;
    /**
     * <pre>
     *卡牌升星
     * </pre>
     *
     * <code>MsgID_Bag_CardUpStar = 510;</code>
     */
    public static final int MsgID_Bag_CardUpStar_VALUE = 510;
    /**
     * <pre>
     *卡牌宿命
     * </pre>
     *
     * <code>MsgID_Bag_CardFate = 511;</code>
     */
    public static final int MsgID_Bag_CardFate_VALUE = 511;
    /**
     * <pre>
     *卡牌宿命列表
     * </pre>
     *
     * <code>MsgID_Bag_CardFateList = 512;</code>
     */
    public static final int MsgID_Bag_CardFateList_VALUE = 512;
    /**
     * <pre>
     *装备强化
     * </pre>
     *
     * <code>MsgID_Bag_EquipIntensify = 513;</code>
     */
    public static final int MsgID_Bag_EquipIntensify_VALUE = 513;
    /**
     * <pre>
     *装备合成
     * </pre>
     *
     * <code>MsgID_Bag_EquipUp = 514;</code>
     */
    public static final int MsgID_Bag_EquipUp_VALUE = 514;
    /**
     * <pre>
     *饰品进阶
     * </pre>
     *
     * <code>MsgID_Bag_AccessoryUp = 515;</code>
     */
    public static final int MsgID_Bag_AccessoryUp_VALUE = 515;
    /**
     * <pre>
     *饰品强化
     * </pre>
     *
     * <code>MsgID_Bag_AccessoryIntensify = 516;</code>
     */
    public static final int MsgID_Bag_AccessoryIntensify_VALUE = 516;
    /**
     * <pre>
     *经验卷轴添加经验
     * </pre>
     *
     * <code>MsgID_Bag_CardAddExp = 517;</code>
     */
    public static final int MsgID_Bag_CardAddExp_VALUE = 517;
    /**
     * <pre>
     *饰品强化经验卷轴升级
     * </pre>
     *
     * <code>MsgID_Bag_AccessoryAddExp = 518;</code>
     */
    public static final int MsgID_Bag_AccessoryAddExp_VALUE = 518;
    /**
     * <pre>
     *卡牌合成
     * </pre>
     *
     * <code>MsgID_Bag_CardSyn = 519;</code>
     */
    public static final int MsgID_Bag_CardSyn_VALUE = 519;
    /**
     * <pre>
     *卡片重生
     * </pre>
     *
     * <code>MsgID_Bag_RebirthCard = 520;</code>
     */
    public static final int MsgID_Bag_RebirthCard_VALUE = 520;
    /**
     * <pre>
     *英魂分解可分解卡牌预览
     * </pre>
     *
     * <code>MsgID_Bag_ResolveCardPreview = 521;</code>
     */
    public static final int MsgID_Bag_ResolveCardPreview_VALUE = 521;
    /**
     * <pre>
     *英魂分解
     * </pre>
     *
     * <code>MsgID_Bag_SoulResolve = 522;</code>
     */
    public static final int MsgID_Bag_SoulResolve_VALUE = 522;
    /**
     * <pre>
     *装备碎片分解
     * </pre>
     *
     * <code>MsgID_Bag_EquipResolve = 523;</code>
     */
    public static final int MsgID_Bag_EquipResolve_VALUE = 523;
    /**
     * <pre>
     *卡牌在战斗卡组下阵
     * </pre>
     *
     * <code>MsgID_Bag_QuitBattleGroup = 524;</code>
     */
    public static final int MsgID_Bag_QuitBattleGroup_VALUE = 524;
    /**
     * <pre>
     *道具使用
     * </pre>
     *
     * <code>MsgID_Bag_UseProp = 525;</code>
     */
    public static final int MsgID_Bag_UseProp_VALUE = 525;
    /**
     * <pre>
     *饰品激活
     * </pre>
     *
     * <code>MsgID_Bag_AccessoryActivated = 526;</code>
     */
    public static final int MsgID_Bag_AccessoryActivated_VALUE = 526;
    /**
     * <pre>
     *上阵卡片替换
     * </pre>
     *
     * <code>MsgID_Bag_BattleCardReset = 527;</code>
     */
    public static final int MsgID_Bag_BattleCardReset_VALUE = 527;
    /**
     * <pre>
     *查看副本进度信息
     * </pre>
     *
     * <code>MsgID_Instance_GetInstanceInfo = 601;</code>
     */
    public static final int MsgID_Instance_GetInstanceInfo_VALUE = 601;
    /**
     * <pre>
     *通过某一副本关卡
     * </pre>
     *
     * <code>MsgID_Instance_PassLevel = 602;</code>
     */
    public static final int MsgID_Instance_PassLevel_VALUE = 602;
    /**
     * <pre>
     *领取副本奖励
     * </pre>
     *
     * <code>MsgID_Instance_ReceiveAward = 603;</code>
     */
    public static final int MsgID_Instance_ReceiveAward_VALUE = 603;
    /**
     * <pre>
     *副本挑战发起
     * </pre>
     *
     * <code>MsgID_Instance_RequestLevelBattle = 604;</code>
     */
    public static final int MsgID_Instance_RequestLevelBattle_VALUE = 604;
    /**
     * <pre>
     *领取关卡宝箱奖励
     * </pre>
     *
     * <code>MsgID_Instance_ReceiveLevelBoxReward = 605;</code>
     */
    public static final int MsgID_Instance_ReceiveLevelBoxReward_VALUE = 605;
    /**
     * <pre>
     *获取最后一次的战斗信息
     * </pre>
     *
     * <code>MsgID_Instance_GetLastPassLevel = 606;</code>
     */
    public static final int MsgID_Instance_GetLastPassLevel_VALUE = 606;
    /**
     * <pre>
     *查看竞技场信息
     * </pre>
     *
     * <code>MsgID_Arena_GetArenaInfo = 701;</code>
     */
    public static final int MsgID_Arena_GetArenaInfo_VALUE = 701;
    /**
     * <pre>
     *竞技场挑战
     * </pre>
     *
     * <code>MsgID_Arena_Challenge = 702;</code>
     */
    public static final int MsgID_Arena_Challenge_VALUE = 702;
    /**
     * <pre>
     *竞技场每日领取奖励
     * </pre>
     *
     * <code>MsgID_Arena_GetDailyReward = 703;</code>
     */
    public static final int MsgID_Arena_GetDailyReward_VALUE = 703;
    /**
     * <pre>
     *竞技场查看排行
     * </pre>
     *
     * <code>MsgID_Arena_PreviewRank = 704;</code>
     */
    public static final int MsgID_Arena_PreviewRank_VALUE = 704;
    /**
     * <pre>
     *兑换竞技场商店奖励
     * </pre>
     *
     * <code>MsgID_Arena_ExchangeReward = 705;</code>
     */
    public static final int MsgID_Arena_ExchangeReward_VALUE = 705;
    /**
     * <pre>
     *竞技场兑换记录
     * </pre>
     *
     * <code>MsgID_Arena_RewardRecord = 706;</code>
     */
    public static final int MsgID_Arena_RewardRecord_VALUE = 706;
    /**
     * <pre>
     *竞技场副本扫荡
     * </pre>
     *
     * <code>MsgID_Arena_Sweep = 707;</code>
     */
    public static final int MsgID_Arena_Sweep_VALUE = 707;
    /**
     * <pre>
     *抽奖
     * </pre>
     *
     * <code>MsgID_Pub_LotteryClick = 801;</code>
     */
    public static final int MsgID_Pub_LotteryClick_VALUE = 801;
    /**
     * <pre>
     *初始化
     * </pre>
     *
     * <code>MsgID_Pub_LotteryInit = 802;</code>
     */
    public static final int MsgID_Pub_LotteryInit_VALUE = 802;
    /**
     * <pre>
     *祭坛初始化
     * </pre>
     *
     * <code>MsgID_Altar_Init = 901;</code>
     */
    public static final int MsgID_Altar_Init_VALUE = 901;
    /**
     * <pre>
     *祭祀
     * </pre>
     *
     * <code>MsgID_Altar_Sacrifice = 902;</code>
     */
    public static final int MsgID_Altar_Sacrifice_VALUE = 902;
    /**
     * <pre>
     *初始化页面信息
     * </pre>
     *
     * <code>MsgID_OfficialWar_InitInfo = 1001;</code>
     */
    public static final int MsgID_OfficialWar_InitInfo_VALUE = 1001;
    /**
     * <pre>
     *查看官阶对应的人员
     * </pre>
     *
     * <code>MsgID_OfficialWar_PreviewRank = 1002;</code>
     */
    public static final int MsgID_OfficialWar_PreviewRank_VALUE = 1002;
    /**
     * <pre>
     *挑战对应官阶
     * </pre>
     *
     * <code>MsgID_OfficialWar_ChallengeRank = 1003;</code>
     */
    public static final int MsgID_OfficialWar_ChallengeRank_VALUE = 1003;
    /**
     * <pre>
     *扫荡对应官阶
     * </pre>
     *
     * <code>MsgID_OfficialWar_SweepRank = 1004;</code>
     */
    public static final int MsgID_OfficialWar_SweepRank_VALUE = 1004;
    /**
     * <pre>
     *每日领取奖励
     * </pre>
     *
     * <code>MsgID_OfficialWar_GetDailyReward = 1005;</code>
     */
    public static final int MsgID_OfficialWar_GetDailyReward_VALUE = 1005;
    /**
     * <pre>
     *兑换商店奖励
     * </pre>
     *
     * <code>MsgID_OfficialWar_ExchangeReward = 1006;</code>
     */
    public static final int MsgID_OfficialWar_ExchangeReward_VALUE = 1006;
    /**
     * <pre>
     *兑换记录
     * </pre>
     *
     * <code>MsgID_OfficialWar_RewardRecord = 1007;</code>
     */
    public static final int MsgID_OfficialWar_RewardRecord_VALUE = 1007;
    /**
     * <pre>
     *积分兑换
     * </pre>
     *
     * <code>MsgID_OfficialWar_IntegralReward = 1008;</code>
     */
    public static final int MsgID_OfficialWar_IntegralReward_VALUE = 1008;
    /**
     * <pre>
     *积分兑换记录
     * </pre>
     *
     * <code>MsgID_OfficialWar_IntegralRewardRecord = 1009;</code>
     */
    public static final int MsgID_OfficialWar_IntegralRewardRecord_VALUE = 1009;
    /**
     * <pre>
     *发起挑战
     * </pre>
     *
     * <code>MsgID_OfficialWar_RequestBattle = 1010;</code>
     */
    public static final int MsgID_OfficialWar_RequestBattle_VALUE = 1010;
    /**
     * <pre>
     *任务列表显示
     * </pre>
     *
     * <code>MsgID_Task_TaskList = 1101;</code>
     */
    public static final int MsgID_Task_TaskList_VALUE = 1101;
    /**
     * <pre>
     *任务领奖
     * </pre>
     *
     * <code>MsgID_Task_TaskReward = 1102;</code>
     */
    public static final int MsgID_Task_TaskReward_VALUE = 1102;
    /**
     * <pre>
     *宝箱领奖
     * </pre>
     *
     * <code>MsgID_Task_TreasureReward = 1103;</code>
     */
    public static final int MsgID_Task_TreasureReward_VALUE = 1103;
    /**
     * <pre>
     *主线任务完成推送
     * </pre>
     *
     * <code>MsgID_Task_TaskMainDoneNotify = 1104;</code>
     */
    public static final int MsgID_Task_TaskMainDoneNotify_VALUE = 1104;
    /**
     * <pre>
     *商店初始化（包含刷新）
     * </pre>
     *
     * <code>MsgID_Store_InitInfo = 1201;</code>
     */
    public static final int MsgID_Store_InitInfo_VALUE = 1201;
    /**
     * <pre>
     *商店购买
     * </pre>
     *
     * <code>MsgID_Store_BuyGoods = 1202;</code>
     */
    public static final int MsgID_Store_BuyGoods_VALUE = 1202;
    /**
     * <pre>
     *次数购买(包含各类挑战，刷新次数)
     * </pre>
     *
     * <code>MsgID_Store_BuyTimes = 1203;</code>
     */
    public static final int MsgID_Store_BuyTimes_VALUE = 1203;
    /**
     * <pre>
     *英雄圣殿初始化页面信息
     * </pre>
     *
     * <code>MsgID_HeroTemple_InitInfo = 1301;</code>
     */
    public static final int MsgID_HeroTemple_InitInfo_VALUE = 1301;
    /**
     * <pre>
     *英雄圣殿挑战
     * </pre>
     *
     * <code>MsgID_HeroTemple_Challenge = 1302;</code>
     */
    public static final int MsgID_HeroTemple_Challenge_VALUE = 1302;
    /**
     * <pre>
     *英雄圣殿扫荡
     * </pre>
     *
     * <code>MsgID_HeroTemple_Sweep = 1303;</code>
     */
    public static final int MsgID_HeroTemple_Sweep_VALUE = 1303;
    /**
     * <pre>
     *邮件列表
     * </pre>
     *
     * <code>MsgID_Mail_List = 1401;</code>
     */
    public static final int MsgID_Mail_List_VALUE = 1401;
    /**
     * <pre>
     *邮件详情
     * </pre>
     *
     * <code>MsgID_Mail_Detail = 1402;</code>
     */
    public static final int MsgID_Mail_Detail_VALUE = 1402;
    /**
     * <pre>
     *领取附件
     * </pre>
     *
     * <code>MsgID_Mail_GetAuxiliary = 1403;</code>
     */
    public static final int MsgID_Mail_GetAuxiliary_VALUE = 1403;
    /**
     * <pre>
     *私信列表
     * </pre>
     *
     * <code>MsgID_Mail_PrivacyMailList = 1404;</code>
     */
    public static final int MsgID_Mail_PrivacyMailList_VALUE = 1404;
    /**
     * <pre>
     *私信详情
     * </pre>
     *
     * <code>MsgID_Mail_PrivacyMailDetail = 1405;</code>
     */
    public static final int MsgID_Mail_PrivacyMailDetail_VALUE = 1405;
    /**
     * <pre>
     *发送回复私信
     * </pre>
     *
     * <code>MsgID_Mail_SendPrivacyMail = 1406;</code>
     */
    public static final int MsgID_Mail_SendPrivacyMail_VALUE = 1406;
    /**
     * <pre>
     *黑名单列表
     * </pre>
     *
     * <code>MsgID_Mail_BlackList = 1407;</code>
     */
    public static final int MsgID_Mail_BlackList_VALUE = 1407;
    /**
     * <pre>
     *添加移除黑名单
     * </pre>
     *
     * <code>MsgID_Mail_AddAndRemoveBlackList = 1408;</code>
     */
    public static final int MsgID_Mail_AddAndRemoveBlackList_VALUE = 1408;
    /**
     * <pre>
     *检测是否具有全员发送权限
     * </pre>
     *
     * <code>MsgID_Mail_CheckSendJurisdiction = 1409;</code>
     */
    public static final int MsgID_Mail_CheckSendJurisdiction_VALUE = 1409;
    /**
     * <pre>
     *新邮件推送
     * </pre>
     *
     * <code>MsgID_Mail_NewMailNotify = 1410;</code>
     */
    public static final int MsgID_Mail_NewMailNotify_VALUE = 1410;
    /**
     * <pre>
     *充值初始化
     * </pre>
     *
     * <code>MsgID_Bonus_RechargeInit = 1501;</code>
     */
    public static final int MsgID_Bonus_RechargeInit_VALUE = 1501;
    /**
     * <pre>
     *充值结果回调
     * </pre>
     *
     * <code>MsgID_Bonus_RechargeResult = 1502;</code>
     */
    public static final int MsgID_Bonus_RechargeResult_VALUE = 1502;
    /**
     * <pre>
     *购买vip礼包
     * </pre>
     *
     * <code>MsgID_Bonus_BuyVipGiftBag = 1503;</code>
     */
    public static final int MsgID_Bonus_BuyVipGiftBag_VALUE = 1503;
    /**
     * <pre>
     *领取月卡奖励
     * </pre>
     *
     * <code>MsgID_Bonus_ReceiveMouthCardReward = 1504;</code>
     */
    public static final int MsgID_Bonus_ReceiveMouthCardReward_VALUE = 1504;
    /**
     * <pre>
     *领取首冲礼包
     * </pre>
     *
     * <code>MsgID_Bonus_ReceiveFirstRechargeReward = 1505;</code>
     */
    public static final int MsgID_Bonus_ReceiveFirstRechargeReward_VALUE = 1505;
    /**
     * <pre>
     *福利面板初始化
     * </pre>
     *
     * <code>MsgID_Bonus_BonusBoardInit = 1506;</code>
     */
    public static final int MsgID_Bonus_BonusBoardInit_VALUE = 1506;
    /**
     * <pre>
     *每日签到
     * </pre>
     *
     * <code>MsgID_Bonus_DailySignReward = 1507;</code>
     */
    public static final int MsgID_Bonus_DailySignReward_VALUE = 1507;
    /**
     * <pre>
     *购买基金
     * </pre>
     *
     * <code>MsgID_Bonus_BuyFund = 1508;</code>
     */
    public static final int MsgID_Bonus_BuyFund_VALUE = 1508;
    /**
     * <pre>
     *领取基金奖励
     * </pre>
     *
     * <code>MsgID_Bonus_ReceiveFundReward = 1509;</code>
     */
    public static final int MsgID_Bonus_ReceiveFundReward_VALUE = 1509;
    /**
     * <pre>
     *累计登陆奖励初始化
     * </pre>
     *
     * <code>MsgID_Bonus_LoginTimesRewardInit = 1510;</code>
     */
    public static final int MsgID_Bonus_LoginTimesRewardInit_VALUE = 1510;
    /**
     * <pre>
     *累计登陆奖励领取
     * </pre>
     *
     * <code>MsgID_Bonus_ReceiveLoginTimesReward = 1511;</code>
     */
    public static final int MsgID_Bonus_ReceiveLoginTimesReward_VALUE = 1511;
    /**
     * <pre>
     *充值检测
     * </pre>
     *
     * <code>MsgID_Bonus_RechargeCheck = 1512;</code>
     */
    public static final int MsgID_Bonus_RechargeCheck_VALUE = 1512;
    /**
     * <pre>
     *远征初始化
     * </pre>
     *
     * <code>MsgID_Expedition_Init = 1601;</code>
     */
    public static final int MsgID_Expedition_Init_VALUE = 1601;
    /**
     * <pre>
     *远征挑战发起
     * </pre>
     *
     * <code>MsgID_Expedition_ChallengeRequest = 1602;</code>
     */
    public static final int MsgID_Expedition_ChallengeRequest_VALUE = 1602;
    /**
     * <pre>
     *远征刷新boss
     * </pre>
     *
     * <code>MsgID_Expedition_FreshBoss = 1603;</code>
     */
    public static final int MsgID_Expedition_FreshBoss_VALUE = 1603;
    /**
     * <pre>
     *远征召唤boss
     * </pre>
     *
     * <code>MsgID_Expedition_CallBoss = 1604;</code>
     */
    public static final int MsgID_Expedition_CallBoss_VALUE = 1604;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static E_MSG_ID valueOf(int value) {
      return forNumber(value);
    }

    public static E_MSG_ID forNumber(int value) {
      switch (value) {
        case 0: return MsgID_NeverUse;
        case 101: return MsgID_System_Regist;
        case 102: return MsgID_System_Login;
        case 103: return MsgID_System_Ping;
        case 104: return MsgID_System_GetCaptcha;
        case 105: return MsgID_System_NotifyAlert;
        case 106: return MsgID_System_Logout;
        case 199: return MsgID_System_SuperLogin;
        case 110: return MsgID_System_BattleReconnect;
        case 111: return MsgID_System_GMCmd;
        case 112: return MsgID_System_LoginOtherPlace;
        case 113: return MsgID_System_CancelWait;
        case 114: return MsgID_System_Offline;
        case 201: return MsgID_War_Create;
        case 202: return MsgID_War_ToBattle;
        case 203: return MsgID_War_SoldierBattleStart;
        case 204: return MsgID_War_SynResult;
        case 205: return MsgID_War_UseSkill;
        case 206: return MsgID_War_AddEffect;
        case 207: return MsgID_War_RemoveEffect;
        case 208: return MsgID_War_UpdateEffectDuration;
        case 209: return MsgID_War_ObjectDie;
        case 210: return MsgID_War_SynPos;
        case 211: return MsgID_War_DoDamage;
        case 212: return MsgID_War_SoldierRoute;
        case 213: return MsgID_War_AttributeUpdate;
        case 214: return MsgID_War_ReadyStart;
        case 215: return MsgID_War_SynBuff;
        case 216: return MsgID_War_SynCountDown;
        case 217: return MsgID_War_Surrender;
        case 218: return MsgID_War_AutoBattle;
        case 219: return MsgID_War_Pause;
        case 301: return MsgID_Player_GetInfo;
        case 302: return MsgID_Player_FlushData;
        case 303: return MsgID_Player_RedPointRemind;
        case 304: return MsgID_Player_SynBaseData;
        case 305: return MsgID_Player_ArenaMatch;
        case 306: return MsgID_Player_CancelArenaMatch;
        case 307: return MsgID_Player_EditPlayerName;
        case 308: return MsgID_Player_EditPlayerAvatar;
        case 309: return MsgID_Player_ChangeConsumeRemindStatus;
        case 310: return MsgID_Player_ChangeEquippedSkill;
        case 311: return MsgID_Player_SettingBoardInit;
        case 312: return MsgID_Player_FlushGoodsGet;
        case 313: return MsgID_Player_GetInstanceRemainChallengeTime;
        case 314: return MsgID_Player_UpdateGuideProgress;
        case 315: return MsgID_Player_GetMobileCaptcha;
        case 316: return MsgID_Player_BindingMobile;
        case 317: return MsgID_Player_CdkUse;
        case 318: return MsgID_Player_FeedBack;
        case 319: return MsgID_Player_RankList;
        case 401: return MsgID_Map_EnterHomeScene;
        case 402: return MsgID_Map_AddBuildingQueue;
        case 403: return MsgID_Map_RemoveBuildingQueue;
        case 404: return MsgID_Map_BuildingFinished;
        case 405: return MsgID_Map_BuildingLevelUp;
        case 406: return MsgID_Map_MoveHome;
        case 501: return MsgID_Bag_SoldierTeamConfig;
        case 502: return MsgID_Bag_SoldierTeamBattle;
        case 503: return MsgID_Bag_CardLevelUp;
        case 504: return MsgID_Bag_MyCard;
        case 505: return MsgID_Bag_MyCardTeam;
        case 506: return MsgID_Bag_SetBattleCardTeam;
        case 507: return MsgID_Bag_SetCardReplace;
        case 508: return MsgID_Bag_CardDetail;
        case 509: return MsgID_Bag_CardUpLv;
        case 510: return MsgID_Bag_CardUpStar;
        case 511: return MsgID_Bag_CardFate;
        case 512: return MsgID_Bag_CardFateList;
        case 513: return MsgID_Bag_EquipIntensify;
        case 514: return MsgID_Bag_EquipUp;
        case 515: return MsgID_Bag_AccessoryUp;
        case 516: return MsgID_Bag_AccessoryIntensify;
        case 517: return MsgID_Bag_CardAddExp;
        case 518: return MsgID_Bag_AccessoryAddExp;
        case 519: return MsgID_Bag_CardSyn;
        case 520: return MsgID_Bag_RebirthCard;
        case 521: return MsgID_Bag_ResolveCardPreview;
        case 522: return MsgID_Bag_SoulResolve;
        case 523: return MsgID_Bag_EquipResolve;
        case 524: return MsgID_Bag_QuitBattleGroup;
        case 525: return MsgID_Bag_UseProp;
        case 526: return MsgID_Bag_AccessoryActivated;
        case 527: return MsgID_Bag_BattleCardReset;
        case 601: return MsgID_Instance_GetInstanceInfo;
        case 602: return MsgID_Instance_PassLevel;
        case 603: return MsgID_Instance_ReceiveAward;
        case 604: return MsgID_Instance_RequestLevelBattle;
        case 605: return MsgID_Instance_ReceiveLevelBoxReward;
        case 606: return MsgID_Instance_GetLastPassLevel;
        case 701: return MsgID_Arena_GetArenaInfo;
        case 702: return MsgID_Arena_Challenge;
        case 703: return MsgID_Arena_GetDailyReward;
        case 704: return MsgID_Arena_PreviewRank;
        case 705: return MsgID_Arena_ExchangeReward;
        case 706: return MsgID_Arena_RewardRecord;
        case 707: return MsgID_Arena_Sweep;
        case 801: return MsgID_Pub_LotteryClick;
        case 802: return MsgID_Pub_LotteryInit;
        case 901: return MsgID_Altar_Init;
        case 902: return MsgID_Altar_Sacrifice;
        case 1001: return MsgID_OfficialWar_InitInfo;
        case 1002: return MsgID_OfficialWar_PreviewRank;
        case 1003: return MsgID_OfficialWar_ChallengeRank;
        case 1004: return MsgID_OfficialWar_SweepRank;
        case 1005: return MsgID_OfficialWar_GetDailyReward;
        case 1006: return MsgID_OfficialWar_ExchangeReward;
        case 1007: return MsgID_OfficialWar_RewardRecord;
        case 1008: return MsgID_OfficialWar_IntegralReward;
        case 1009: return MsgID_OfficialWar_IntegralRewardRecord;
        case 1010: return MsgID_OfficialWar_RequestBattle;
        case 1101: return MsgID_Task_TaskList;
        case 1102: return MsgID_Task_TaskReward;
        case 1103: return MsgID_Task_TreasureReward;
        case 1104: return MsgID_Task_TaskMainDoneNotify;
        case 1201: return MsgID_Store_InitInfo;
        case 1202: return MsgID_Store_BuyGoods;
        case 1203: return MsgID_Store_BuyTimes;
        case 1301: return MsgID_HeroTemple_InitInfo;
        case 1302: return MsgID_HeroTemple_Challenge;
        case 1303: return MsgID_HeroTemple_Sweep;
        case 1401: return MsgID_Mail_List;
        case 1402: return MsgID_Mail_Detail;
        case 1403: return MsgID_Mail_GetAuxiliary;
        case 1404: return MsgID_Mail_PrivacyMailList;
        case 1405: return MsgID_Mail_PrivacyMailDetail;
        case 1406: return MsgID_Mail_SendPrivacyMail;
        case 1407: return MsgID_Mail_BlackList;
        case 1408: return MsgID_Mail_AddAndRemoveBlackList;
        case 1409: return MsgID_Mail_CheckSendJurisdiction;
        case 1410: return MsgID_Mail_NewMailNotify;
        case 1501: return MsgID_Bonus_RechargeInit;
        case 1502: return MsgID_Bonus_RechargeResult;
        case 1503: return MsgID_Bonus_BuyVipGiftBag;
        case 1504: return MsgID_Bonus_ReceiveMouthCardReward;
        case 1505: return MsgID_Bonus_ReceiveFirstRechargeReward;
        case 1506: return MsgID_Bonus_BonusBoardInit;
        case 1507: return MsgID_Bonus_DailySignReward;
        case 1508: return MsgID_Bonus_BuyFund;
        case 1509: return MsgID_Bonus_ReceiveFundReward;
        case 1510: return MsgID_Bonus_LoginTimesRewardInit;
        case 1511: return MsgID_Bonus_ReceiveLoginTimesReward;
        case 1512: return MsgID_Bonus_RechargeCheck;
        case 1601: return MsgID_Expedition_Init;
        case 1602: return MsgID_Expedition_ChallengeRequest;
        case 1603: return MsgID_Expedition_FreshBoss;
        case 1604: return MsgID_Expedition_CallBoss;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<E_MSG_ID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        E_MSG_ID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<E_MSG_ID>() {
            public E_MSG_ID findValueByNumber(int number) {
              return E_MSG_ID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.douqu.game.core.protobuf.SGMainProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final E_MSG_ID[] VALUES = values();

    public static E_MSG_ID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private E_MSG_ID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:E_MSG_ID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014SGMain.proto*\365\002\n\nE_MSG_TYPE\022\024\n\020MsgType" +
      "_NeverUse\020\000\022\022\n\rMsgType_Close\020\217N\022\023\n\016MsgTy" +
      "pe_Battle\020\310\001\022\023\n\016MsgType_Player\020\254\002\022\022\n\rMsg" +
      "Type_World\020\220\003\022\020\n\013MsgType_Bag\020\364\003\022\025\n\020MsgTy" +
      "pe_Instance\020\330\004\022\022\n\rMsgType_Arena\020\274\005\022\024\n\017Ms" +
      "gType_Lottery\020\240\006\022\022\n\rMsgType_Altar\020\204\007\022\030\n\023" +
      "MsgType_OfficialWar\020\350\007\022\021\n\014MsgType_Task\020\314" +
      "\010\022\022\n\rMsgType_Store\020\260\t\022\027\n\022MsgType_HeroTem" +
      "ple\020\224\n\022\021\n\014MsgType_Mail\020\370\n\022\022\n\rMsgType_Bon" +
      "us\020\334\013\022\027\n\022MsgType_Expedition\020\300\014*\361#\n\010E_MSG",
      "_ID\022\022\n\016MsgID_NeverUse\020\000\022\027\n\023MsgID_System_" +
      "Regist\020e\022\026\n\022MsgID_System_Login\020f\022\025\n\021MsgI" +
      "D_System_Ping\020g\022\033\n\027MsgID_System_GetCaptc" +
      "ha\020h\022\034\n\030MsgID_System_NotifyAlert\020i\022\027\n\023Ms" +
      "gID_System_Logout\020j\022\034\n\027MsgID_System_Supe" +
      "rLogin\020\307\001\022 \n\034MsgID_System_BattleReconnec" +
      "t\020n\022\026\n\022MsgID_System_GMCmd\020o\022 \n\034MsgID_Sys" +
      "tem_LoginOtherPlace\020p\022\033\n\027MsgID_System_Ca" +
      "ncelWait\020q\022\030\n\024MsgID_System_Offline\020r\022\025\n\020" +
      "MsgID_War_Create\020\311\001\022\027\n\022MsgID_War_ToBattl",
      "e\020\312\001\022!\n\034MsgID_War_SoldierBattleStart\020\313\001\022" +
      "\030\n\023MsgID_War_SynResult\020\314\001\022\027\n\022MsgID_War_U" +
      "seSkill\020\315\001\022\030\n\023MsgID_War_AddEffect\020\316\001\022\033\n\026" +
      "MsgID_War_RemoveEffect\020\317\001\022#\n\036MsgID_War_U" +
      "pdateEffectDuration\020\320\001\022\030\n\023MsgID_War_Obje" +
      "ctDie\020\321\001\022\025\n\020MsgID_War_SynPos\020\322\001\022\027\n\022MsgID" +
      "_War_DoDamage\020\323\001\022\033\n\026MsgID_War_SoldierRou" +
      "te\020\324\001\022\036\n\031MsgID_War_AttributeUpdate\020\325\001\022\031\n" +
      "\024MsgID_War_ReadyStart\020\326\001\022\026\n\021MsgID_War_Sy" +
      "nBuff\020\327\001\022\033\n\026MsgID_War_SynCountDown\020\330\001\022\030\n",
      "\023MsgID_War_Surrender\020\331\001\022\031\n\024MsgID_War_Aut" +
      "oBattle\020\332\001\022\024\n\017MsgID_War_Pause\020\333\001\022\031\n\024MsgI" +
      "D_Player_GetInfo\020\255\002\022\033\n\026MsgID_Player_Flus" +
      "hData\020\256\002\022 \n\033MsgID_Player_RedPointRemind\020" +
      "\257\002\022\035\n\030MsgID_Player_SynBaseData\020\260\002\022\034\n\027Msg" +
      "ID_Player_ArenaMatch\020\261\002\022\"\n\035MsgID_Player_" +
      "CancelArenaMatch\020\262\002\022 \n\033MsgID_Player_Edit" +
      "PlayerName\020\263\002\022\"\n\035MsgID_Player_EditPlayer" +
      "Avatar\020\264\002\022+\n&MsgID_Player_ChangeConsumeR" +
      "emindStatus\020\265\002\022%\n MsgID_Player_ChangeEqu",
      "ippedSkill\020\266\002\022\"\n\035MsgID_Player_SettingBoa" +
      "rdInit\020\267\002\022\037\n\032MsgID_Player_FlushGoodsGet\020" +
      "\270\002\0220\n+MsgID_Player_GetInstanceRemainChal" +
      "lengeTime\020\271\002\022%\n MsgID_Player_UpdateGuide" +
      "Progress\020\272\002\022\"\n\035MsgID_Player_GetMobileCap" +
      "tcha\020\273\002\022\037\n\032MsgID_Player_BindingMobile\020\274\002" +
      "\022\030\n\023MsgID_Player_CdkUse\020\275\002\022\032\n\025MsgID_Play" +
      "er_FeedBack\020\276\002\022\032\n\025MsgID_Player_RankList\020" +
      "\277\002\022\035\n\030MsgID_Map_EnterHomeScene\020\221\003\022\037\n\032Msg" +
      "ID_Map_AddBuildingQueue\020\222\003\022\"\n\035MsgID_Map_",
      "RemoveBuildingQueue\020\223\003\022\037\n\032MsgID_Map_Buil" +
      "dingFinished\020\224\003\022\036\n\031MsgID_Map_BuildingLev" +
      "elUp\020\225\003\022\027\n\022MsgID_Map_MoveHome\020\226\003\022 \n\033MsgI" +
      "D_Bag_SoldierTeamConfig\020\365\003\022 \n\033MsgID_Bag_" +
      "SoldierTeamBattle\020\366\003\022\032\n\025MsgID_Bag_CardLe" +
      "velUp\020\367\003\022\025\n\020MsgID_Bag_MyCard\020\370\003\022\031\n\024MsgID" +
      "_Bag_MyCardTeam\020\371\003\022 \n\033MsgID_Bag_SetBattl" +
      "eCardTeam\020\372\003\022\035\n\030MsgID_Bag_SetCardReplace" +
      "\020\373\003\022\031\n\024MsgID_Bag_CardDetail\020\374\003\022\027\n\022MsgID_" +
      "Bag_CardUpLv\020\375\003\022\031\n\024MsgID_Bag_CardUpStar\020",
      "\376\003\022\027\n\022MsgID_Bag_CardFate\020\377\003\022\033\n\026MsgID_Bag" +
      "_CardFateList\020\200\004\022\035\n\030MsgID_Bag_EquipInten" +
      "sify\020\201\004\022\026\n\021MsgID_Bag_EquipUp\020\202\004\022\032\n\025MsgID" +
      "_Bag_AccessoryUp\020\203\004\022!\n\034MsgID_Bag_Accesso" +
      "ryIntensify\020\204\004\022\031\n\024MsgID_Bag_CardAddExp\020\205" +
      "\004\022\036\n\031MsgID_Bag_AccessoryAddExp\020\206\004\022\026\n\021Msg" +
      "ID_Bag_CardSyn\020\207\004\022\032\n\025MsgID_Bag_RebirthCa" +
      "rd\020\210\004\022!\n\034MsgID_Bag_ResolveCardPreview\020\211\004" +
      "\022\032\n\025MsgID_Bag_SoulResolve\020\212\004\022\033\n\026MsgID_Ba" +
      "g_EquipResolve\020\213\004\022\036\n\031MsgID_Bag_QuitBattl",
      "eGroup\020\214\004\022\026\n\021MsgID_Bag_UseProp\020\215\004\022!\n\034Msg" +
      "ID_Bag_AccessoryActivated\020\216\004\022\036\n\031MsgID_Ba" +
      "g_BattleCardReset\020\217\004\022#\n\036MsgID_Instance_G" +
      "etInstanceInfo\020\331\004\022\035\n\030MsgID_Instance_Pass" +
      "Level\020\332\004\022 \n\033MsgID_Instance_ReceiveAward\020" +
      "\333\004\022&\n!MsgID_Instance_RequestLevelBattle\020" +
      "\334\004\022)\n$MsgID_Instance_ReceiveLevelBoxRewa" +
      "rd\020\335\004\022$\n\037MsgID_Instance_GetLastPassLevel" +
      "\020\336\004\022\035\n\030MsgID_Arena_GetArenaInfo\020\275\005\022\032\n\025Ms" +
      "gID_Arena_Challenge\020\276\005\022\037\n\032MsgID_Arena_Ge",
      "tDailyReward\020\277\005\022\034\n\027MsgID_Arena_PreviewRa" +
      "nk\020\300\005\022\037\n\032MsgID_Arena_ExchangeReward\020\301\005\022\035" +
      "\n\030MsgID_Arena_RewardRecord\020\302\005\022\026\n\021MsgID_A" +
      "rena_Sweep\020\303\005\022\033\n\026MsgID_Pub_LotteryClick\020" +
      "\241\006\022\032\n\025MsgID_Pub_LotteryInit\020\242\006\022\025\n\020MsgID_" +
      "Altar_Init\020\205\007\022\032\n\025MsgID_Altar_Sacrifice\020\206" +
      "\007\022\037\n\032MsgID_OfficialWar_InitInfo\020\351\007\022\"\n\035Ms" +
      "gID_OfficialWar_PreviewRank\020\352\007\022$\n\037MsgID_" +
      "OfficialWar_ChallengeRank\020\353\007\022 \n\033MsgID_Of" +
      "ficialWar_SweepRank\020\354\007\022%\n MsgID_Official",
      "War_GetDailyReward\020\355\007\022%\n MsgID_OfficialW" +
      "ar_ExchangeReward\020\356\007\022#\n\036MsgID_OfficialWa" +
      "r_RewardRecord\020\357\007\022%\n MsgID_OfficialWar_I" +
      "ntegralReward\020\360\007\022+\n&MsgID_OfficialWar_In" +
      "tegralRewardRecord\020\361\007\022$\n\037MsgID_OfficialW" +
      "ar_RequestBattle\020\362\007\022\030\n\023MsgID_Task_TaskLi" +
      "st\020\315\010\022\032\n\025MsgID_Task_TaskReward\020\316\010\022\036\n\031Msg" +
      "ID_Task_TreasureReward\020\317\010\022\"\n\035MsgID_Task_" +
      "TaskMainDoneNotify\020\320\010\022\031\n\024MsgID_Store_Ini" +
      "tInfo\020\261\t\022\031\n\024MsgID_Store_BuyGoods\020\262\t\022\031\n\024M",
      "sgID_Store_BuyTimes\020\263\t\022\036\n\031MsgID_HeroTemp" +
      "le_InitInfo\020\225\n\022\037\n\032MsgID_HeroTemple_Chall" +
      "enge\020\226\n\022\033\n\026MsgID_HeroTemple_Sweep\020\227\n\022\024\n\017" +
      "MsgID_Mail_List\020\371\n\022\026\n\021MsgID_Mail_Detail\020" +
      "\372\n\022\034\n\027MsgID_Mail_GetAuxiliary\020\373\n\022\037\n\032MsgI" +
      "D_Mail_PrivacyMailList\020\374\n\022!\n\034MsgID_Mail_" +
      "PrivacyMailDetail\020\375\n\022\037\n\032MsgID_Mail_SendP" +
      "rivacyMail\020\376\n\022\031\n\024MsgID_Mail_BlackList\020\377\n" +
      "\022%\n MsgID_Mail_AddAndRemoveBlackList\020\200\013\022" +
      "%\n MsgID_Mail_CheckSendJurisdiction\020\201\013\022\035",
      "\n\030MsgID_Mail_NewMailNotify\020\202\013\022\035\n\030MsgID_B" +
      "onus_RechargeInit\020\335\013\022\037\n\032MsgID_Bonus_Rech" +
      "argeResult\020\336\013\022\036\n\031MsgID_Bonus_BuyVipGiftB" +
      "ag\020\337\013\022\'\n\"MsgID_Bonus_ReceiveMouthCardRew" +
      "ard\020\340\013\022+\n&MsgID_Bonus_ReceiveFirstRechar" +
      "geReward\020\341\013\022\037\n\032MsgID_Bonus_BonusBoardIni" +
      "t\020\342\013\022 \n\033MsgID_Bonus_DailySignReward\020\343\013\022\030" +
      "\n\023MsgID_Bonus_BuyFund\020\344\013\022\"\n\035MsgID_Bonus_" +
      "ReceiveFundReward\020\345\013\022%\n MsgID_Bonus_Logi" +
      "nTimesRewardInit\020\346\013\022(\n#MsgID_Bonus_Recei",
      "veLoginTimesReward\020\347\013\022\036\n\031MsgID_Bonus_Rec" +
      "hargeCheck\020\350\013\022\032\n\025MsgID_Expedition_Init\020\301" +
      "\014\022&\n!MsgID_Expedition_ChallengeRequest\020\302" +
      "\014\022\037\n\032MsgID_Expedition_FreshBoss\020\303\014\022\036\n\031Ms" +
      "gID_Expedition_CallBoss\020\304\014B3\n\034com.douqu." +
      "game.core.protobufB\013SGMainProto\252\002\005UBaseb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
